create extension if not exists pg_trgm;
create index if not exists idx_companies_domain on companies(domain);
create index if not exists idx_companies_name_trgm on companies using gin (name gin_trgm_ops);
create index if not exists idx_people_company_id on people(company_id);
create index if not exists idx_people_domain on people(domain);
create index if not exists idx_people_linkedin on people(linkedin_url);
create index if not exists idx_signals_company_id on signals(company_id);
create index if not exists idx_signals_person_id on signals(person_id);
create index if not exists idx_signals_type on signals(type);
create index if not exists idx_signals_occurred_at on signals(occurred_at desc);
create index if not exists idx_signals_domain on signals(domain);
create index if not exists idx_signals_hash on signals(hash);
create index if not exists idx_signals_tags on signals using gin (tags);
create index if not exists idx_social_url on social_signals(url);
create index if not exists idx_social_hash on social_signals(hash);
create index if not exists idx_social_occurred_at on social_signals(occurred_at desc);
create index if not exists idx_social_domain on social_signals(domain);
create index if not exists idx_opps_run_id on opportunities(run_id);
create index if not exists idx_opps_company_id on opportunities(company_id);
create index if not exists idx_opps_status on opportunities(status);
create index if not exists idx_opps_conf on opportunities(confidence desc);
create index if not exists idx_opps_created on opportunities(created_at desc);
create index if not exists idx_opps_domain on opportunities(domain);
create index if not exists idx_scans_status on scans(status);
create index if not exists idx_scans_started on scans(started_at desc);
create index if not exists idx_outreach_opp on outreach(opportunity_id);
create index if not exists idx_outreach_status on outreach(status);
create index if not exists idx_emb_entity on embeddings(entity_type, entity_id);
create index if not exists idx_emb_vector on embeddings using ivfflat (embedding vector_cosine_ops) with (lists = 100);
